name = "Claris"
license = "MIT"
licenselink = "https://github.com/simonheimlicher/hugo-claris/blob/main/LICENSE"
description = "Fluid and responsive theme for a professional portfolio website or blog"
homepage = "https://claris.heimlicher.com/"
tags = ["Fluid", "Responsive", "Multilingual", "Portfolio", "Dark", "Light"]
features = ["Fluid", "Responsive", "Multilingual", "Dark mode"]
min_version = "0.121.0"

[author]
  name = "Simon Heimlicher"
  homepage = "https://simon.heimlicher.com"
